import { profile } from 'console';
import { Formik } from 'formik';
import type { NextPage } from 'next';
import Head from 'next/head';

import { useEffect } from 'react';

import { useSelector, useDispatch } from 'react-redux';
import styles from '../../styles/Home.module.css';
import { AppDispatch } from '../app/store';
import { selectProfile, selectProfiles } from '../app/store/slices/authSlice';
import {
  consolefetch,
  fetchAsyncNewPortfolio,
  fetchPostEnd,
  fetchPostStart,
  selectPortfolios,
} from '../app/store/slices/portfolioSlice';
import { Avatar } from '../components/Avatar';
import { Card } from '../components/Card';
import { Like } from '../components/Like';

const Home: NextPage = () => {
  const myprofile = useSelector(selectProfile);
  const profiles = useSelector(selectProfiles);
  const portfolios = useSelector(selectPortfolios);
  const dispatch: AppDispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {portfolios.map((portfolio, i) => (
        <div
          key={i}
          className='overflow-hidden mx-auto max-w-2xl bg-white dark:bg-gray-800 rounded-lg shadow-md'
        >
          <Card portfolioid={portfolio.id} author={portfolio.author} portfolioimg={portfolio.img} />
        </div>
      ))}
    </>
  );
};

export default Home;
