import type { NextPage } from 'next';
import { GetStaticPaths, GetStaticProps, GetStaticPropsContext } from 'next';

import Head from 'next/head';

import { useEffect, useState } from 'react';
import { FaSearch } from 'react-icons/fa';
import Modal from 'react-modal';

import { useSelector } from 'react-redux';
import {
  selectPortfolios,
  selectTags,
  fetchAsyncGetPopular,
} from '../app/store/slices/portfolioSlice';
import { PROPS_PORTFOLIO, PROPS_TAG } from '../app/store/types';
import { Card } from '../components/Card';

Modal.setAppElement('#__next');

const apiUrl = process.env.NEXT_PUBLIC_API_ENDOPOINT;

interface PortfolioProps {
  populars: any;
}

const Popular: React.FC<PortfolioProps> = ({ populars }) => {
  return (
    <>
      <Head>
        <title>Connect</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='m-5 text-2xl font-extrabold text-center'>人気作品ランキング</div>

      <div className='flex flex-wrap'>
        {populars.map((popular, i) => (
          <div key={i} className='flex lg:w-1/4'>
            <Card
              title={popular.title}
              portfolioid={popular.id}
              author={popular.author}
              portfolioimg={popular.img}
            />
          </div>
        ))}
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const res = await fetch(`${apiUrl}api/popular`);
  const populars = await res.json();

  return {
    props: { populars },
    revalidate: 1,
  };
};

export default Popular;
